export enum PageLinks {
  Home = 'home',
  Panel = 'panel',
  Account = 'account',
  BaseInfo = 'base-info',
  Staff = 'staff',

  Role = 'role',
  User = 'user',

  Evaluation='evaluation',
  EvaluationGroup='evaluation-group',
  EvaluationIndicator='evaluation-indicator',
  SecretaryEvaluation='secretary-evaluation',
  EvaluationCourse='evaluation-course',
  Score='score',
  DepartmentHolding = 'department-holding',
  DepartmentMeeting = 'department-meeting',
  DepartmentMeetingMember = 'department-meeting-member',
  ProceedingsDepartment = 'proceedings-department',
  DepartmentMeetingAttendees = 'department-meeting-attendees',
  SessionApprovals = 'session-approvals',
  Task = 'task',
  TaskGroup = 'task-group',
  CooperationType = 'cooperation-type',
  ActivityCase = 'activity-case',
  LessonType = 'lesson-type',
  StudyDegree = 'study-degree',
  AcademicYear = 'academic-year',
  ExecutiveCalendar = 'ExecutiveCalendar',
  StudyField = 'study-field',
  StudyGrade = 'study-grade',
  Lesson = 'lesson',
  Topic = 'topic',
  Position = 'position',
  AssignTask = 'assignTask',
  AssignPosition='assignPosition',
  DepartmentActivity = 'department-activity',
  DepartmentMember = 'department-member',
  DepartmentActivityType = 'department-activity-type',
  DepartmentLesson = 'department-lesson',
  DepartmentSchedule = 'department-schedule',
  Department = 'department',
  DepartmentManagement = 'department-management',

  StaffComplementary = 'staff-complementary/:staffId',

  StaffAddress = 'staff-address',
  StaffFinancial = 'staff-financial',
  StaffFurtherInformation = 'staff-further-information',
  StaffDocument = 'staff-document',
  StaffResume = 'staff-resume',
  StaffActivity = 'staff-activity',
  StaffFamily = 'staff-family',
  StaffCooperation = 'staff-cooperation',
  StaffSacrifice = 'staff-sacrifice',
  StaffUploadDocument = 'staff-upload-document',

  Profile = 'profile',

  AddPage = 'add',
  EditPage = 'edit/:id',

  Auth = 'auth',
  Login = 'login',
  ForgetPassword = 'forget-password',
  ResetPassword = 'reset-password',

}
